---
abstract: 'Fundamental Goedel number calculator'
author:
  - 'turugina <turugina@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Goedel
requires:
  Carp: 0
  Exporter: 0
  Math::BigInt: 0
  Math::Prime::Util: 0
  Test::More: 0
version: 0.04
