--- #YAML:1.0
name:                Math-Goedel
version:             0.03
abstract:            Fundamental Goedel number calculator
license:             ~
author:              
    - KATOU Akira (turugina) <turugina@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Exporter:                      5.57
    List::MoreUtils:               0
    List::Util:                    0
    Math::Prime::XS:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
